const players = [
{
    name : "ronaldo",
    age : 38,
    country : "Portugal",   
    position : "Forward",
    photo : "https://example.com/ronaldo.jpg",
},
{
    name : "messi",
    age : 36,
    country : "Argentina",   
    position : "Forward",
    photo : "https://example.com/messi.jpg",
},
{
    name : "neymar",
    age : 31,
    country : "Brazil",   
    position : "Forward",
    photo : "https://example.com/neymar.jpg",
},
{
    name : "mbappe",
    age : 24,
    country : "France",   
    position : "Forward",
    photo : "https://example.com/mbappe.jpg",
},
{
    name : "lewandowski",
    age : 35,
    country : "Poland",   
    position : "Forward",
    photo : "https://example.com/lewandowski.jpg",
},
{
    name : "salah",
    age : 31,
    country : "Egypt",   
    position : "Forward",
    photo : "https://example.com/salah.jpg",
},
{
    name : "kane",
    age : 30,
    country : "England",   
    position : "Forward",
    photo : "https://example.com/kane.jpg",
},
{
    name : "de bruyne",
    age : 32,
    country : "Belgium",   
    position : "Midfielder",
    photo : "https://example.com/de_bruyne.jpg",
},
{
    name : "modric",
    age : 38,
    country : "Croatia",   
    position : "Midfielder",
    photo : "https://example.com/modric.jpg",
},
{
    name : "casemiro",
    age : 31,
    country : "Brazil",   
    position : "Midfielder",
    photo : "https://example.com/casemiro.jpg",
}
,{
    name : "kante",
    age : 32,
    country : "France",   
    position : "Midfielder",
    photo : "https://example.com/kante.jpg",
},
{
    name : "bruno fernandes",
    age : 29,
    country : "Portugal",   
    position : "Midfielder",
    photo : "https://example.com/bruno_fernandes.jpg",
},
{
    name : "goretzka",
    age : 28,
    country : "Germany",   
    position : "Midfielder",
    photo : "https://example.com/goretzka.jpg",
},
{
    name : "van dijk",
    age : 32,
    country : "Netherlands",   
    position : "Defender",
    photo : "https://example.com/van_dijk.jpg",
},
{
    name : "alaba",
    age : 31,
    country : "Austria",   
    position : "Defender",
    photo : "https://example.com/alaba.jpg",
},
{
    name : "hernandez",
    age : 26,
    country : "France",   
    position : "Defender",
    photo : "https://example.com/hernandez.jpg",
},
{
    name : "alexander-arnold",
    age : 25,
    country : "England",   
    position : "Defender",
    photo : "https://example.com/alexander_arnold.jpg",
},
{
    name : "maguire",
    age : 30,
    country : "England",   
    position : "Defender",
    photo : "https://example.com/maguire.jpg",
},
{
    name : "ramos",
    age : 37,
    country : "Spain",   
    position : "Defender",
    photo : "https://example.com/ramos.jpg",
},
{
    name : "neuer",
    age : 37,
    country : "Germany",   
    position : "Goalkeeper",
    photo : "https://example.com/neuer.jpg",
},
{
    name : "courtois",
    age : 31,
    country : "Belgium",   
    position : "Goalkeeper",
    photo : "https://example.com/courtois.jpg",
},
{
    name: 'ederson',
     age: 30,
     country: 'Brazil',
     position: 'Goalkeeper',
     photo: 'https://example.com/ederson.jpg',
}


]